#!/bin/bash

##################
# USER VARIABLES #
##################

#Change to your remote name
remote_name='remote'

#################
# END VARIABLES #
#################

dir=`pwd`

cd ~/vimwiki
git pull $remote master

cd $dir

