#!/bin/bash

######################
# No changes to make #
######################

dir=`pwd`

remote_name='__REMOTE_NAME__'
wiki_dir='__WIKI_DIR__'

cd $wiki_dir
git pull $remote_name master

cd $dir

