#!/data/data/com.termux/files/usr/bin/bash

######################
# No changes to make #
######################

dir=`pwd`

remote_name='__REMOTE_NAME__'

cd ~/vimwiki
git pull $remote master

cd $dir

