#!/bin/bash

##################
# USER VARIABLES #
##################

#Change to your git server details
server='git@domain:/path/repo.git'

#Change to your remote name
remote_name='remote'

#Change to your wiki directory
wiki_dir='~/vimwiki'

#################
# END VARIABLES #
#################

dir=`pwd`

cd $wiki_dir

git init
git add .
git commit -m "Initial commit - automatic by noteserv"
git remote add $remote_name $server
git push -u $remote_name master

cd $dir

cat upload_linux_osx | sed "s/__REMOTE_NAME__/$remote_name/g;s|__WIKI_DIR__|$wiki_dir|g" > upload

cat download_linux_osx | sed "s/__REMOTE_NAME__/$remote_name/g;s|__WIKI__DIR|$wiki_dir|g" > download

