#!/bin/bash

##################
# USER VARIABLES #
##################

#Make sure this matches the setup file!
repo_name='vimwiki.git'

#################
# END VARIABLES #
#################

echo 'Adding user'
adduser --system --shell /bin/bash \
    --gecos 'git version control'  \
    --group --home /home/git git

echo 'Setting password'
passwd git

echo 'Creating git repo'
su git -c "cd ~; mkdir $repo_name; cd $repo_name; git init --bare"

echo 'Done! Make sure you set up the client setup file with the same'
echo 'parameters here.'

