#!/bin/bash

##################
# USER VARIABLES #
##################

#Change to your git server details
server='git@domain:/path/repo.git'

#Change to your remote name
remote_name='remote'

#################
# END VARIABLES #
#################

dir=`pwd`

cd ~/vimwiki

git init
git add .
git commit -m "Initial commit - automatic by noteserv"
git remote add $remote $server
git push -u $remote master

cat upload_linux_osx | sed "s/__REMOTE_NAME__/$remote_name/g" > upload
cat download_linux_osx | sed "s/__REMOTE_NAME__/$remote_name/g" > download

cd $dir

