#!/bin/bash

##################
# USER VARIABLES #
##################

#Change to desired commit message, leave blank to open editor
commit_msg="Update $(date +'%a %F %I:%M')"

#################
# END VARIABLES #
#################

#Save current dir
dir=`pwd`

cd ~/vimwiki

remote_name='__REMOTE_NAME__'

if [[ -z $commit_msg  ]]; then
    git add .
    git commit
    git push -u $remote_name master
else
    git add .
    git commit -m "$commit_msg"
    git push -u $remote_name master
fi

cd $dir

